---
- hosts: 172.16.1.4
  gather_facts: no
  tasks:
  - name: run show version on remote devices
    iosxr_command:
      commands:
        - ping 8.8.8.8
#        - traceroute 8.8.8.8
        - show route 8.8.8.8
    register: result

  - name: debug
    debug:
      msg:
        - "{{ result.stdout_lines[0] }}"
        - "{{ result.stdout_lines[1] }}"
#        - "{{ result.stdout_lines[2] }}"
